In [1]:
import numpy as np

In [2]:
li = np.array([[1,2,3],[4,5,6],[7,8,9]])
li

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
inserted = np.insert(li, 0, 1, axis=1)
inserted

array([[1, 1, 2, 3],
       [1, 4, 5, 6],
       [1, 7, 8, 9]])

In [4]:
inserted.shape[0]

3

In [5]:
y = np.zeros(inserted.shape[0])
y

array([0., 0., 0.])

In [6]:
inserted


array([[1, 1, 2, 3],
       [1, 4, 5, 6],
       [1, 7, 8, 9]])

In [7]:
inserted = np.insert(inserted, 0, 333, axis=1)
inserted

array([[333,   1,   1,   2,   3],
       [333,   1,   4,   5,   6],
       [333,   1,   7,   8,   9]])

In [8]:
n = inserted.shape[0]
n

3

In [9]:
m = inserted.shape[1]
m

5

In [10]:
arr = inserted
arr

array([[333,   1,   1,   2,   3],
       [333,   1,   4,   5,   6],
       [333,   1,   7,   8,   9]])

In [11]:
num_features = arr.shape[1]
num_points = arr.shape[0]
print("features: ", num_features)
print("entries:  ", num_points)

features:  5
entries:   3


In [12]:
import csc665.linear as lin

In [13]:
regressor = lin.LinearRegression(.01, 200)

Initializing


In [14]:
import numpy as np
import sklearn.linear_model as sk_linear
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

In [15]:
RANDOM_STATE = 3454
data_df = pd.read_csv("http://www-bcf.usc.edu/~gareth/ISL/Income2.csv")
data_df.drop("Unnamed: 0", axis=1, inplace=True)
X = data_df.drop('Income', axis=1).values
y = data_df["Income"].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=RANDOM_STATE)

In [16]:
regressor.fit(X_train, y_train)

fitting


NameError: name 'n' is not defined

In [ ]:
# make a prediction for each row in the training set
h = np.zeros(X_train.shape[0])
h.shape
for i in range(24):
    h[i] = regressor.predict(X_train[i])
    print(h[i])


In [ ]:
h = regressor.predict(X[0])
h